[workspace]
resolver = "3"
members = [
    "crates/anon-ast",
    "crates/anon-cli",
    "crates/anon-core",
    "crates/anon-compiler",
    "crates/anon-driver",
    "crates/anon-typer",
    "crates/anon-codegen",
]
